### ISSUE TITLE
Kernel execution errors not being rendered in OutputArea

### ISSUE THREAD

**Issue by sglyon** [jupyter-book/thebe#759]
Hello! I'm using thebe in a project and have run into a snag. 

Kernel outputs are shown nicely (including widgets and multimedia) when code succeeds, however when there is a runtime error in the kernel nothing is shown.

I recorded a video clip walking through the error: https://app.screencastify.com/v3/watch/492g6QRsO1NjMOjdrg13

You can also reproduce by

1. going to the "simple" demo ([here](https://jupyter-book.github.io/thebe/) or by running the demo via the main branch of this repo)
2. Activating the kernel
3. Replacing the input of the code cell  with code that would trigger a Python exception (I just put `assert False`)
4. Running the code

What you **will** see is no rendered output in the `OutputArea`, but you will see the traceback printed to the javascript console

What we **want** to see is the errors rendered in the `OutputArea`.

**Comment by sglyon** [comment]
Hi team, sorry to nudge here. If anyone has an idea of where I could start looking I would be happy to attempt a pull request

thanks!

**Comment by stevejpurves** [comment]
This seems like a regression as previously we have always rendered errors, will take a look @sglyon

**Comment by stevejpurves** [comment]
fix in place, will go out on next release!!

**Comment by sglyon** [comment]
Amazing. Thank you @stevejpurves 

I will test this out and hope for the best ;)

**Comment by sglyon** [comment]
Thank you @stevejpurves I just updated based on a build from `main` and it works great ;)
